---
apiVersion: v1
kind: Service
metadata:
  name: drupal
spec:
  type: ClusterIP  # Cambiado a ClusterIP para usar con Ingress
  ports:
    - port: 8080   # Cambiado para coincidir con el puerto de Ingress
      targetPort: 80
  selector:
    app: drupal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - image: drupal:9
        name: drupal
        env:
          - name: DRUPAL_DB_HOST
            value: wordpress-mysql
          - name: DRUPAL_DB_USER
            value: wordpress
          - name: DRUPAL_DB_PASSWORD
            value: password
          - name: DRUPAL_DB_NAME
            value: wordpress
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-persistent-storage
          mountPath: /var/www/html/sites/default/files
      volumes:
      - name: drupal-persistent-storage
        persistentVolumeClaim:
          claimName: drupal-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/drupal # Directorio en el nodo local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drupal-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drupal
                port:
                  number: 8080
