apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data/nfs/drupal   # Directorio en el servidor NFS
    server: 54.152.250.154  # IP del servidor NFS 
  persistentVolumeReclaimPolicy: Retain
